name = "apps-telegram"
compatibility_date = "2024-01-01"

# 🔥 Esto es clave
[assets]
directory = "./dist"
not_found_handling = "single-page-application"

# Opcional (pero recomendado)
[env.production]
routes = [
  { pattern = "apps-telegram.prod.trelkbot.com/*", zone_name = "trelkbot.com" }
]